// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'StyleUserContainer': string;
  'StyleUserContainerLoading': string;
}
export const cssExports: CssExports;
export default cssExports;
