// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'city': string;
  'itemsMarketImage': string;
  'itemsMarketInfor': string;
  'price': string;
}
export const cssExports: CssExports;
export default cssExports;
