// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'friendItem': string;
  'friendItemImage': string;
  'friendModal': string;
  'friendTooltip': string;
  'itemTooltip': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
