// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'loadingbar': string;
  'progress-animation': string;
  'progressbar': string;
}
export const cssExports: CssExports;
export default cssExports;
