// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ItemContent': string;
  'ItemContentRecord': string;
  'ItemContentRecordGroup': string;
  'ItemContentRecordImage': string;
  'ItemContentRecordReverd': string;
}
export const cssExports: CssExports;
export default cssExports;
