// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ItemContent': string;
  'ItemContentComment': string;
  'ItemContentHeader': string;
  'ItemContentMain': string;
  'ItemImage': string;
  'ItemsComment': string;
  'ItemsCommentAction': string;
  'ItemsCommentChild': string;
}
export const cssExports: CssExports;
export default cssExports;
