// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemPostElement': string;
  'itemPostElementContent': string;
  'itemPostElementHeader': string;
  'itemPostElementHeaderContent': string;
  'itemPostElementSocial': string;
  'itemPostElementSocialContent': string;
  'itemPostElementSocialLike': string;
  'itemPostElementSocialTag': string;
  'itemPostElementSocialViewAll': string;
}
export const cssExports: CssExports;
export default cssExports;
