// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'createPost': string;
  'createPostButton': string;
}
export const cssExports: CssExports;
export default cssExports;
