// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'createPost': string;
  'createPostContentAdd': string;
  'createPostContentImg': string;
  'createPostHeader': string;
  'createPostHeaderUser': string;
  'createPostWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
