// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'listFriend': string;
  'listFriendContent': string;
  'listFriendHeader': string;
  'listFriendItem': string;
}
export const cssExports: CssExports;
export default cssExports;
