// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'viewUser': string;
  'viewUserImage': string;
  'viewUserInforCenter': string;
  'viewUserInforCenterItem': string;
  'viewUserInforTop': string;
}
export const cssExports: CssExports;
export default cssExports;
