// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown': string;
  'dropdownAfter': string;
  'dropdownBefore': string;
  'dropdownItem': string;
}
export const cssExports: CssExports;
export default cssExports;
