// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ItemsComment': string;
  'ItemsCommentAction': string;
  'ItemsCommentChild': string;
  'ItemsCommentChildActive': string;
}
export const cssExports: CssExports;
export default cssExports;
