// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'StylePostUserComponent': string;
  'StylePostUserMain': string;
  'StylePostUserMainOverLay': string;
}
export const cssExports: CssExports;
export default cssExports;
